spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.1.234.51/opaas?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: opaas
    password: opaas
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapperLocations: classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.ai.user.repository